#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ktp-filetransfer-handler
Version  : 18.12.2
Release  : 1
URL      : https://download.kde.org/stable/applications/18.12.2/src/ktp-filetransfer-handler-18.12.2.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.2/src/ktp-filetransfer-handler-18.12.2.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.2/src/ktp-filetransfer-handler-18.12.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: ktp-filetransfer-handler-data = %{version}-%{release}
Requires: ktp-filetransfer-handler-license = %{version}-%{release}
Requires: ktp-filetransfer-handler-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : ktp-common-internals-dev
BuildRequires : telepathy-qt-dev

%description
This is the Telepathy-KDE file transfer handler
It basically does 2 thigs
* Send files to your contact
* Receive files from your contact

%package data
Summary: data components for the ktp-filetransfer-handler package.
Group: Data

%description data
data components for the ktp-filetransfer-handler package.


%package license
Summary: license components for the ktp-filetransfer-handler package.
Group: Default

%description license
license components for the ktp-filetransfer-handler package.


%package locales
Summary: locales components for the ktp-filetransfer-handler package.
Group: Default

%description locales
locales components for the ktp-filetransfer-handler package.


%prep
%setup -q -n ktp-filetransfer-handler-18.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557035271
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1557035271
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktp-filetransfer-handler
cp COPYING %{buildroot}/usr/share/package-licenses/ktp-filetransfer-handler/COPYING
pushd clr-build
%make_install
popd
%find_lang ktp-filetransfer-handler

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/ktp-filetransfer-handler

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.KTp.FileTransferHandler.service
/usr/share/telepathy/clients/KTp.FileTransferHandler.client

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktp-filetransfer-handler/COPYING

%files locales -f ktp-filetransfer-handler.lang
%defattr(-,root,root,-)

